package com.mitsuki.jlpt.app.constants

const val WORD_KIND = "WORD_KIND"
const val TTS_KIND = "TTS_KIND"
const val WORD_VERSION = "WORD_VERSION"
const val WORD_VERSION_TEMP = "WORD_VERSION_TEMP"

const val TESTING_KIND_RANGE = "TESTING_KIND_RANGE"
const val TESTING_DISPLAY_RANGE = "TESTING_DISPLAY_RANGE"
const val TESTING_JUDGE_RANGE = "TESTING_JUDGE_RANGE"


